### ISSUE TITLE
pyenv doctor now fails: cc1: error: bad value 'generic64' for '-march=' switch

### ISSUE THREAD

**Issue by draeath** [pyenv/pyenv-doctor#13]
I ran a `pyenv update` today and, since then, `pyenv doctor` fails with "C compiler cannot create executables"

- RHEL 8 x86_64
- GCC versions tested:
  - gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16) (Base OS)
  - gcc (GCC) 12.1.1 20220628 (Red Hat 12.1.1-3) (via gcc-toolset-12)
- pyenv version: 2.3.12-6-gc8c324af / [gc8c324af](/pyenv/pyenv/commit/c8c324afb42040ac41a71311eb8ccdaf259c7798)
- pyenv-doctor version: (how to check?) / bad83e51e1409665de6cb37537cfc1e02e154bec

config.log section of interest:

    (skipped output)
    
      $ ./configure --prefix=/tmp/pyenv-doctor.20230202134917.4043118/prefix --enable-shared --libdir=/tmp/pyenv-doctor.20230202134917.4043118/prefix/lib --with-cpython --enable-optimizations
    
    (skipped output)
    
    configure:2403: checking whether the C compiler works
    configure:2425: gcc  -pipe -m64 -march=generic64 -mtune=native -I/tmp/pyenv-doctor.20230202134917.4043118/prefix/include -L/tmp/pyenv-doctor.20230202134917.4043118/prefix/lib -Wl,-rpath,/tmp/pyenv-doctor.20230202134917.4043118/prefix/lib conftest.c  >&5
    cc1: error: bad value 'generic64' for '-march=' switch
    cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client rocketlake icelake-server cascadelake tigerlake cooperlake sapphirerapids alderlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 x86-64-v2 x86-64-v3 x86-64-v4 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 znver3 btver1 btver2 native
    configure:2429: $? = 1
    configure:2467: result: no
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "pyenv-doctor"
    | #define PACKAGE_TARNAME "pyenv-doctor"
    | #define PACKAGE_VERSION "0.0.1"
    | #define PACKAGE_STRING "pyenv-doctor 0.0.1"
    | #define PACKAGE_BUGREPORT "yamashita@geishatokyo.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | int
    | main ()
    | {
    | 
    |   ;
    |   return 0;
    | }
    configure:2472: error: in `/tmp/python-build.20230202134917.4043135/python-pyenv-doctor':
    configure:2474: error: C compiler cannot create executables
    See `config.log' for more details
    
    (skipped output)

**Comment by native-api** [comment]
"error: C compiler cannot create executables" usually means that you've passed incorrect compiler flags.

The compiler output tells you the specifics:

```
cc1: error: bad value 'generic64' for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client rocketlake icelake-server cascadelake tigerlake cooperlake sapphirerapids alderlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 x86-64-v2 x86-64-v3 x86-64-v4 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 znver3 btver1 btver2 native
```

**Comment by draeath** [comment]
@native-api shoot, sorry! my environment got polluted somehow. I indeed had this set, somehow.

I still have a problem after cleaning that up, though. `--enable-shared` is getting set, somehow, and that's not in my environment:

    [bransfp@ginnungagap ~]$ set | grep -- '--enable-shared'
    [bransfp@ginnungagap ~]$

This is also causing a 'C compiler cannot create executables' error.

Might this be a problem within `pyenv-build` instead?

EDIT again: I think this is coming from [here](/pyenv/pyenv/pull/2592#issuecomment-1414270629) but, as I note there, I'm not sure which repo this should be reported to.

**Comment by native-api** [comment]
> I still have a problem after cleaning that up, though. `--enable-shared` is getting set, somehow, and that's not in my environment:

`--enable-shared` is intended: https://github.com/pyenv/pyenv/pull/2554

The error has nothing to do with it.

**Comment by draeath** [comment]
Except adding `--disable-shared` to CONFIGURE_OPTS allows it to work...?

**Comment by draeath** [comment]
OK, so I am confused. If I purge my environment, pyenv doctor just breaks, because `--enable-shared` is passed in that test.

This *doesn't* break on your host(s)?

**Comment by draeath** [comment]
OK, and now it's not a problem. Clearly, my workstation is haunted. I apologize for wasting your time @native-api

**Comment by native-api** [comment]
I've worked in the IT long enough to know that there's no such thing as haunting :slightly_smiling_face: .

The problem that you've reported is clearly from the incorrect `-march=generic64` flag, whatever is setting it.

**Comment by draeath** [comment]
That was the original problem, for sure. But the --enable-shared was getting in there *somehow* even after I pulled it out of my dotfiles and `unset` it in my shell.

Been doing this nonsense for 15 years myself. While haunting doesn't happen, unexpected side-effects and bad (human) memory certainly does, lol

**Comment by native-api** [comment]
`--enable-shared` is set by Pyenv as I've mentioned above and it's by design. And it's _not_ the source of the problem that you've reported.

**Comment by draeath** [comment]
@native-api to be clear: it *did* show up in config.log after removing the bad mtune/march args. Adding --disable-shared fixed it.

However, I re-ran the doctor command once more without that set, and it didn't complain again. There was one instance where it, 100%, said invalid argument about `--enable-shared`. Why it was a problem there and only the one time? That's why i joked about haunting.

It's possible something else was going on. This came up with me troubleshooting why `resolve_link()` wasn't being defined - I had to remove libexec/pyenv-realpath.dylib in the middle of all that. I don't recall why that was there.
